version: '3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    image: lucasbdourado/tomcat-vim
    container_name: tomcat-9.0
    networks:
      - userapi
    ports:
      - "8000:8080"

  mysql:
    image: mysql:8.0
    container_name: mysql-8.0
    networks:
      - userapi
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_api

networks:
  userapi:
    driver: bridge